import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { toast } from "sonner";
import { api, apiError } from "@/api";

export default function AccountExtras({ orders, refreshWish, wishlistRef }) {
  const [wishlist, setWishlist] = useState([]); const [coupons, setCoupons] = useState([]); const [returns, setReturns] = useState([]);
  const load = useCallback(() => Promise.all([api.get("/api/wishlist"), api.get("/api/content/coupons"), api.get("/api/returns")]).then(([wishlistResponse, couponResponse, returnResponse]) => { setWishlist(wishlistResponse.data); setCoupons(couponResponse.data); setReturns(returnResponse.data); }).catch((error) => toast.error(apiError(error))), []);
  useEffect(() => { load(); }, [load]);
  const removeWishlist = async (product) => { try { await api.delete(`/api/wishlist/${product.id}`); setWishlist((items) => items.filter((item) => item.id !== product.id)); refreshWish(); toast.success("Removed from wishlist"); } catch (error) { toast.error(apiError(error)); } };
  const requestReturn = async (order) => { try { await api.post("/api/returns", { title: `Return request: ${order.order_number}`, description: "Customer requested a return from My Orders", status: "requested", data: { order_id: order.id } }); toast.success("Return request submitted"); load(); } catch (error) { toast.error(apiError(error)); } };
  return <><section className="account-section" id="wishlist" ref={wishlistRef} data-testid="account-wishlist-section"><div className="panel-head"><h2>My Wishlist</h2><span>{wishlist.length} saved products</span></div>{wishlist.length ? <div className="account-wishlist-grid">{wishlist.map((product) => <article key={product.id} data-testid={`wishlist-product-${product.id}`}><img src={product.images?.[0]} alt={product.name} /><div><b>{product.name}</b><small>₹{Number(product.price).toLocaleString("en-IN")}</small></div><Link to={`/product/${product.id}`}>View</Link><button onClick={() => removeWishlist(product)} data-testid={`remove-wishlist-${product.id}`}>Remove</button></article>)}</div> : <p className="account-muted" data-testid="wishlist-empty-state">Save products from any product page to see them here.</p>}</section><section className="account-section coupon-account-section" id="coupons" data-testid="account-coupons-section"><div className="panel-head"><h2>Available Coupons</h2><Link to="/cart" data-testid="account-coupons-cart-link">Go to checkout</Link></div>{coupons.length ? <div className="coupon-account-grid">{coupons.map((coupon) => <article key={coupon.id} data-testid={`account-coupon-${coupon.id}`}><span>{coupon.data?.discount || "DEAL"}</span><div><b>{coupon.data?.code || coupon.title}</b><small>{coupon.description || "Apply at checkout"}</small></div><Link to="/cart">Use now</Link></article>)}</div> : <p className="account-muted">No active coupons right now.</p>}</section><section className="account-section" data-testid="account-returns-section"><div className="panel-head"><h2>Returns</h2><span>{returns.length} requests</span></div>{orders.length ? orders.map((order) => <div className="return-order-row" key={order.id}><span><b>{order.order_number}</b><small>{order.status.replaceAll("_", " ")}</small></span>{returns.some((request) => request.data?.order_id === order.id) ? <em data-testid={`return-requested-${order.id}`}>Return requested</em> : <button onClick={() => requestReturn(order)} data-testid={`request-return-${order.id}`}>Request return</button>}</div>) : <p className="account-muted">Your eligible orders will appear here.</p>}</section></>;
}