import { useEffect, useState } from "react";
import { Banknote, Building2, CreditCard, KeyRound, Landmark, Percent, Save, ShieldCheck, Smartphone, Wallet } from "lucide-react";
import { toast } from "sonner";
import { api, apiError } from "@/api";

const initial = { razorpay_key_id: "", razorpay_key_secret: "", razorpay_webhook_secret: "", mode: "test", upi_enabled: true, upi_id: "", card_enabled: true, netbanking_enabled: true, cod_enabled: true, wallet_enabled: true, bank_transfer_enabled: true, bank_account_name: "", bank_account_number: "", bank_ifsc_code: "", partial_payment_enabled: false, partial_payment_percent: 100 };
const methods = [["upi_enabled", "UPI / QR", "Razorpay QR and UPI apps", Smartphone], ["bank_transfer_enabled", "Personal UPI QR", "Paytm, PhonePe, GPay + admin proof review", Landmark], ["card_enabled", "Cards", "Credit & debit cards", CreditCard], ["netbanking_enabled", "Net Banking", "All major banks", Building2], ["wallet_enabled", "Store Wallet", "Use customer wallet balance", Wallet], ["cod_enabled", "Cash on Delivery", "Pay when delivered", Banknote]];

export default function AdminPaymentSettings() {
  const [settings, setSettings] = useState(initial); const [saving, setSaving] = useState(false);
  useEffect(() => { api.get("/api/admin/payment-settings").then(({ data }) => setSettings((current) => ({ ...current, ...data }))).catch((error) => toast.error(apiError(error))); }, []);
  const set = (key, value) => setSettings((current) => ({ ...current, [key]: value }));
  const save = async (event) => { event.preventDefault(); setSaving(true); try { const { data } = await api.put("/api/admin/payment-settings", settings); setSettings((current) => ({ ...current, ...data, razorpay_key_secret: "", razorpay_webhook_secret: "" })); toast.success("Payment settings are live"); } catch (error) { toast.error(apiError(error)); } finally { setSaving(false); } };
  return <form className="admin-manager pay-settings" onSubmit={save} data-testid="payment-settings-form">
    <section className="admin-panel pay-connection"><div className="panel-head"><div><span className="pay-kicker"><ShieldCheck size={14} /> PAYMENT CONTROL</span><h2>Razorpay connection</h2><span>Keys remain server-side and are never shown to customers.</span></div><span className={`pay-mode-badge ${settings.mode}`} data-testid="payment-mode-badge">{settings.mode === "live" ? "LIVE MODE" : "TEST MODE"}</span></div><div className="pay-mode-tabs" data-testid="razorpay-mode-select"><button type="button" className={settings.mode === "test" ? "active" : ""} onClick={() => set("mode", "test")} data-testid="razorpay-mode-test-button">Test mode</button><button type="button" className={settings.mode === "live" ? "active" : ""} onClick={() => set("mode", "live")} data-testid="razorpay-mode-live-button">Live mode</button></div><div className="pay-grid"><label className="pay-field"><span><KeyRound size={13} /> Key ID</span><input value={settings.razorpay_key_id || ""} onChange={(event) => set("razorpay_key_id", event.target.value)} placeholder="rzp_live_..." data-testid="razorpay-key-id-input" /></label><label className="pay-field"><span><KeyRound size={13} /> Key Secret</span><input type="password" value={settings.razorpay_key_secret || ""} onChange={(event) => set("razorpay_key_secret", event.target.value)} placeholder={settings.razorpay_key_secret_set ? "Saved securely — enter only to replace" : "Enter Key Secret"} data-testid="razorpay-key-secret-input" /></label><label className="pay-field pay-field-wide"><span><ShieldCheck size={13} /> Webhook Secret <em>Optional</em></span><input type="password" value={settings.razorpay_webhook_secret || ""} onChange={(event) => set("razorpay_webhook_secret", event.target.value)} placeholder={settings.razorpay_webhook_secret_set ? "Saved securely — enter only to replace" : "Enter webhook signing secret"} data-testid="razorpay-webhook-secret-input" /></label></div></section>
    <section className="admin-panel"><div className="panel-head"><div><span className="pay-kicker"><Landmark size={14} /> PERSONAL UPI QR</span><h2>Your UPI receiving details</h2><span>Customer QR, Google Pay, PhonePe और Paytm payment links इसी UPI ID से बनेंगे. PIN/OTP कभी collect नहीं होता.</span></div></div><div className="pay-grid bank-details"><label className="pay-field"><span>Personal UPI ID</span><input value={settings.upi_id || ""} onChange={(event) => set("upi_id", event.target.value)} placeholder="yourname@bank" data-testid="merchant-upi-id-input" /></label><label className="pay-field"><span>UPI recipient name</span><input value={settings.bank_account_name || ""} onChange={(event) => set("bank_account_name", event.target.value)} placeholder="Your name" data-testid="bank-account-name-input" /></label><label className="pay-field"><span>Account number <em>Optional fallback</em></span><input value={settings.bank_account_number || ""} onChange={(event) => set("bank_account_number", event.target.value.replace(/\s/g, ""))} placeholder="Bank account number" data-testid="bank-account-number-input" /></label><label className="pay-field"><span>IFSC code <em>Optional fallback</em></span><input value={settings.bank_ifsc_code || ""} onChange={(event) => set("bank_ifsc_code", event.target.value.toUpperCase())} placeholder="ABCD0123456" data-testid="bank-ifsc-input" /></label></div></section>
    <section className="admin-panel"><div className="panel-head"><div><span className="pay-kicker"><CreditCard size={14} /> CHECKOUT METHODS</span><h2>Customer payment choices</h2><span>Switch off करने पर option checkout से तुरंत हटेगा।</span></div></div><div className="pay-methods">{methods.map(([key, title, detail, Icon]) => <label className={`pay-method ${settings[key] ? "on" : ""}`} key={key}><span className="pay-method-icon"><Icon size={16} /></span><span className="pay-method-copy"><b>{title}</b><small>{detail}</small></span><input type="checkbox" checked={settings[key]} onChange={(event) => set(key, event.target.checked)} data-testid={`payment-toggle-${key}`} /><i className="pay-switch" /></label>)}</div></section>
    <section className="admin-panel pay-advance-panel"><div className="panel-head"><div><span className="pay-kicker"><Percent size={14} /> PARTIAL PAYMENT</span><h2>Advance collection</h2><span>Only for Razorpay online payment methods.</span></div><label className="pay-method"><span className="pay-method-icon"><Percent size={16} /></span><span className="pay-method-copy"><b>Enable partial payment</b><small>Collect a fixed advance percentage</small></span><input type="checkbox" checked={settings.partial_payment_enabled} onChange={(event) => set("partial_payment_enabled", event.target.checked)} data-testid="partial-payment-toggle" /><i className="pay-switch" /></label></div><label className="pay-field partial-percent"><span>Advance amount (%)</span><div className="advance-input"><input type="range" min="10" max="100" value={settings.partial_payment_percent} onChange={(event) => set("partial_payment_percent", Number(event.target.value))} disabled={!settings.partial_payment_enabled} data-testid="partial-percent-slider" /><input type="number" min="10" max="100" value={settings.partial_payment_percent} onChange={(event) => set("partial_payment_percent", Number(event.target.value))} disabled={!settings.partial_payment_enabled} data-testid="partial-percent-input" /><b>%</b></div></label></section>
    <button className="primary-btn pay-save" disabled={saving} data-testid="save-payment-settings-button"><Save size={15} /> {saving ? "Saving…" : "Save payment controls"}</button>
  </form>;
}