import { useCallback, useEffect, useState } from "react";
import { MinusCircle, PlusCircle, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { api, apiError } from "@/api";

const money = (value = 0) => `₹${Number(value).toLocaleString("en-IN")}`;

export default function AdminWalletManager() {
  const [wallets, setWallets] = useState([]); const [selected, setSelected] = useState(null); const [form, setForm] = useState({ amount: "", kind: "credit", note: "Admin wallet adjustment" }); const [transactions, setTransactions] = useState([]); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const { data } = await api.get("/api/admin/wallets"); setWallets(data); } catch (error) { toast.error(apiError(error)); } }, []);
  useEffect(() => { load(); }, [load]);
  const openWallet = async (wallet) => { setSelected(wallet); setTransactions([]); try { const { data } = await api.get(`/api/admin/wallets/${wallet.user_id}/transactions`); setTransactions(data); } catch (error) { toast.error(apiError(error)); } };
  const adjust = async (event) => { event.preventDefault(); if (!selected) return; setBusy(true); try { const { data } = await api.post("/api/admin/wallets/adjust", { user_id: selected.user_id, amount: Number(form.amount), kind: form.kind, note: form.note }); setSelected(data); setForm({ ...form, amount: "" }); toast.success(`Wallet ${form.kind} completed`); await load(); const response = await api.get(`/api/admin/wallets/${selected.user_id}/transactions`); setTransactions(response.data); } catch (error) { toast.error(apiError(error)); } finally { setBusy(false); } };
  return <div className="admin-manager" data-testid="wallet-manager"><section className="admin-panel table-panel admin-wide"><div className="panel-head"><div><h2>Customer wallets</h2><span>Credit and debit balances with a live audit trail.</span></div><WalletCards size={18} /></div><table data-testid="wallets-table"><thead><tr><th>Customer</th><th>Available balance</th><th>Last updated</th><th>Control</th></tr></thead><tbody>{wallets.map((wallet) => <tr key={wallet.user_id}><td><b>{wallet.user_name}</b><small>{wallet.user_email}</small></td><td className="wallet-amount">{money(wallet.balance)}</td><td>{new Date(wallet.updated_at).toLocaleDateString("en-IN")}</td><td><button onClick={() => openWallet(wallet)} data-testid={`open-wallet-${wallet.user_id}`}>Manage wallet</button></td></tr>)}</tbody></table></section>{selected && <section className="admin-panel wallet-detail" data-testid="wallet-adjustment-panel"><div className="panel-head"><div><h2>{selected.user_name}'s wallet</h2><strong className="wallet-balance" data-testid="selected-wallet-balance">{money(selected.balance)}</strong></div><button onClick={() => setSelected(null)} data-testid="close-wallet-panel-button">Close</button></div><form className="wallet-form" onSubmit={adjust}><select value={form.kind} onChange={(event) => setForm({ ...form, kind: event.target.value })} data-testid="wallet-adjustment-kind"><option value="credit">Credit balance</option><option value="debit">Debit balance</option></select><input type="number" min="1" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} placeholder="Amount in ₹" required data-testid="wallet-adjustment-amount" /><input value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} placeholder="Adjustment note" required data-testid="wallet-adjustment-note" /><button className="primary-btn" disabled={busy} data-testid="submit-wallet-adjustment-button">{form.kind === "credit" ? <PlusCircle size={15} /> : <MinusCircle size={15} />}{busy ? "Updating…" : `${form.kind === "credit" ? "Credit" : "Debit"} wallet`}</button></form><div className="wallet-ledger"><h3>Transaction ledger</h3>{transactions.length ? transactions.map((transaction) => <div className="ledger-row" key={transaction.id} data-testid={`wallet-transaction-${transaction.id}`}><span className={transaction.kind === "credit" ? "credit" : "debit"}>{transaction.kind === "credit" ? "+" : "−"}{money(transaction.amount)}</span><p>{transaction.note}<small>{new Date(transaction.created_at).toLocaleString("en-IN")}</small></p><b>{money(transaction.balance_after)}</b></div>) : <p data-testid="wallet-empty-ledger">No wallet transactions yet.</p>}</div></section>}</div>;
}