import { useCallback, useEffect, useState } from "react";
import { Check, Gavel, Plus, Trash2, UserRoundCheck } from "lucide-react";
import { toast } from "sonner";
import { api, apiError } from "@/api";

const money = (value = 0) => `₹${Number(value).toLocaleString("en-IN")}`;
const slugify = (value) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

export function CategoryManager() {
  const [rows, setRows] = useState([]); const [form, setForm] = useState({ id: "", name: "", slug: "", image: "", active: true });
  const load = useCallback(async () => { try { const { data } = await api.get("/api/admin/categories"); setRows(data); } catch (error) { toast.error(apiError(error)); } }, []); useEffect(() => { load(); }, [load]);
  const save = async (event) => { event.preventDefault(); try { const payload = { ...form, slug: form.slug || slugify(form.name), image: form.image || null }; if (form.id) await api.patch(`/api/admin/categories/${form.id}`, payload); else await api.post("/api/admin/categories", payload); setForm({ id: "", name: "", slug: "", image: "", active: true }); toast.success("Category saved"); load(); } catch (error) { toast.error(apiError(error)); } };
  return <div className="admin-manager"><section className="admin-panel resource-editor"><div className="panel-head"><div><h2>{form.id ? "Edit category" : "Add category"}</h2><span>Live category visibility is controlled here.</span></div></div><form className="resource-form" onSubmit={save}><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value, slug: form.id ? form.slug : slugify(event.target.value) })} placeholder="Category name" required data-testid="category-name-input" /><input value={form.slug} onChange={(event) => setForm({ ...form, slug: event.target.value })} placeholder="Category slug" required data-testid="category-slug-input" /><input value={form.image || ""} onChange={(event) => setForm({ ...form, image: event.target.value })} placeholder="Optional image URL" data-testid="category-image-input" /><label className="publish-check"><input type="checkbox" checked={form.active} onChange={(event) => setForm({ ...form, active: event.target.checked })} data-testid="category-active-checkbox" /> Show on website</label><button className="primary-btn" data-testid="save-category-button"><Check size={15} /> Save category</button></form></section><section className="admin-panel table-panel admin-wide"><table data-testid="categories-table"><thead><tr><th>Category</th><th>Slug</th><th>Website state</th><th>Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.name}</td><td>{row.slug}</td><td><span className={row.active ? "status-live" : "status-draft"}>{row.active ? "LIVE" : "HIDDEN"}</span></td><td className="row-controls"><button onClick={() => setForm({ ...row, image: row.image || "" })} data-testid={`edit-category-${row.id}`}>Edit</button><button onClick={async () => { try { await api.patch(`/api/admin/categories/${row.id}`, { ...row, active: !row.active }); toast.success("Category visibility updated"); load(); } catch (error) { toast.error(apiError(error)); } }} data-testid={`toggle-category-${row.id}`}>{row.active ? "Hide" : "Publish"}</button></td></tr>)}</tbody></table></section></div>;
}

export function UserManager({ admins = false }) {
  const [rows, setRows] = useState([]); const load = useCallback(async () => { try { const { data } = await api.get(`/api/admin/users${admins ? "?role=admin" : ""}`); setRows(data); } catch (error) { toast.error(apiError(error)); } }, [admins]); useEffect(() => { load(); }, [load]);
  return <section className="admin-panel table-panel admin-wide" data-testid="user-manager"><div className="panel-head"><div><h2>{admins ? "Admin users" : "Customers & admin users"}</h2><span>Live access control for MobileCart accounts.</span></div><UserRoundCheck size={18} /></div><table data-testid={`${admins ? "admin" : "users"}-table`}><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>State</th><th>Control</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.name}</td><td>{row.email}</td><td>{row.role}</td><td><span className={row.active === false ? "status-draft" : "status-live"}>{row.active === false ? "INACTIVE" : "ACTIVE"}</span></td><td><button onClick={async () => { try { await api.patch(`/api/admin/users/${row.id}`, { active: row.active === false }); toast.success("User access updated"); load(); } catch (error) { toast.error(apiError(error)); } }} data-testid={`toggle-user-${row.id}`}>{row.active === false ? "Activate" : "Deactivate"}</button></td></tr>)}</tbody></table></section>;
}

export function WorkflowManager({ kind }) {
  const [rows, setRows] = useState([]); const [products, setProducts] = useState([]); const load = useCallback(async () => { const path = { orders: "/api/orders", payments: "/api/admin/payments", auctions: "/api/admin/auctions", returns: "/api/admin/returns", support: "/api/admin/support-tickets" }[kind]; try { const { data } = await api.get(path); setRows(data.items || data); } catch (error) { toast.error(apiError(error)); } }, [kind]); useEffect(() => { load(); if (kind === "auctions") api.get("/api/admin/products?page_size=100").then(({ data }) => setProducts(data.items)).catch(() => setProducts([])); }, [kind, load]);
  const run = async (row) => { try { if (kind === "orders") await api.patch(`/api/admin/orders/${row.id}/status?status=shipped`); if (kind === "payments") await api.patch(`/api/admin/payments/${row.id}`, { status: "captured" }); if (kind === "auctions") await api.post(`/api/admin/auctions/${row.id}/close`); if (kind === "returns" || kind === "support") await api.patch(`/api/admin/${kind === "returns" ? "returns" : "support-tickets"}/${row.id}`, { title: row.title, description: row.description, status: kind === "returns" ? "approved" : "resolved", data: row.data }); toast.success("Live workflow updated"); load(); } catch (error) { toast.error(apiError(error)); } };
  const createAuction = async () => { if (!products[0]) { toast.error("Add a product first"); return; } try { const start = new Date(); const end = new Date(Date.now() + 86400000); await api.post("/api/admin/auctions", { product_id: products[0].id, starting_price: Math.max(1, Math.round(products[0].price * 0.5)), bid_increment: 100, starts_at: start.toISOString(), ends_at: end.toISOString() }); toast.success("Auction published"); load(); } catch (error) { toast.error(apiError(error)); } };
  const label = { orders: "Orders", payments: "Payments", auctions: "Auctions", returns: "Returns & Refunds", support: "Support Tickets" }[kind]; return <section className="admin-panel table-panel admin-wide" data-testid={`${kind}-manager`}><div className="panel-head"><div><h2>{label}</h2><span>Actions update live operations immediately.</span></div>{kind === "auctions" && <button onClick={createAuction} data-testid="create-auction-button"><Plus size={14} /> Create live auction</button>}</div><table data-testid={`${kind}-table`}><thead><tr><th>Record</th><th>Value</th><th>Status</th><th>Control</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.order_number || row.title || row.product?.name || row.id}</td><td>{row.total ? money(row.total) : row.current_bid ? money(row.current_bid) : row.description || "—"}</td><td>{row.payment?.status || row.status}</td><td><button onClick={() => run(row)} data-testid={`${kind}-action-${row.id}`}>{kind === "orders" ? "Mark shipped" : kind === "payments" ? "Capture" : kind === "auctions" ? "Close auction" : <><Check size={14} /> Resolve</>}</button></td></tr>)}</tbody></table>{!rows.length && <p className="admin-empty-copy">No {label.toLowerCase()} yet.</p>}</section>;
}