import { useEffect, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { Bell, ChevronRight, Gavel, LayoutDashboard, Menu, Package, Settings, ShoppingCart, Tags, TrendingUp, Users, WalletCards, X } from "lucide-react";
import { toast } from "sonner";
import { api, apiError } from "@/api";
import AdminProductManager from "@/components/AdminProductManager";
import AdminResourceManager from "@/components/AdminResourceManager";
import AdminWalletManager from "@/components/AdminWalletManager";
import { CategoryManager, UserManager, WorkflowManager } from "@/components/AdminOperationsManager";

const sectionGroups = [
  ["dashboard", "Dashboard", "dashboard", LayoutDashboard], ["users", "Users", "users", Users], ["vendors", "Vendors", "resource", Users], ["products", "Products", "products", Package], ["categories", "Categories", "categories", Tags], ["brands", "Brands", "resource", Tags], ["orders", "Orders", "orders", Package], ["payments", "Payments", "payments", WalletCards], ["wallet-withdrawals", "Wallet & Withdrawals", "wallet", WalletCards], ["auctions", "Auctions", "auctions", Gavel], ["campaigns", "Campaigns", "resource", TrendingUp], ["coupons", "Coupons", "resource", Tags], ["announcements", "Announcements", "resource", Bell], ["subscriptions", "Subscriptions", "resource", Package], ["app-manager", "App Manager", "resource", LayoutDashboard], ["banners", "Banners", "resource", Tags], ["notifications", "Notifications", "resource", Bell], ["returns-refunds", "Returns & Refunds", "returns", Package], ["shipping", "Shipping", "resource", Package], ["gst-tax", "GST & Tax", "resource", Tags], ["reports-analytics", "Reports & Analytics", "reports", TrendingUp], ["support-tickets", "Support Tickets", "support", Bell], ["admin-users", "Admin Users", "admin-users", Users], ["settings", "Settings", "resource", Settings],
];
const money = (value = 0) => `₹${Number(value).toLocaleString("en-IN")}`;

function Sidebar({ active, open, onClose }) { return <aside className={`admin-sidebar ${open ? "open" : ""}`} data-testid="admin-sidebar"><div className="admin-brand"><Link to="/admin" data-testid="admin-brand-link"><div className="brand"><span className="brand-mark"><ShoppingCart size={20} /></span><span className="brand-text"><b>MobileCart</b><small>Operations Console</small></span></div></Link><button onClick={onClose} className="mobile-only icon-btn" data-testid="close-admin-menu"><X /></button></div><nav>{sectionGroups.map(([id, label, , Icon]) => <Link to={id === "dashboard" ? "/admin" : `/admin/${id}`} className={active === id ? "active" : ""} key={id} data-testid={`admin-nav-${id}`}><Icon />{label}</Link>)}</nav><div className="admin-user" data-testid="admin-user-info"><span>AD</span><div><b>Admin</b><small>Live control enabled</small></div><ChevronRight size={16} /></div></aside>; }

function Header({ title, onMenu, query, setQuery }) { return <header className="admin-top"><button className="mobile-only icon-btn" onClick={onMenu} data-testid="admin-menu-button"><Menu /></button><div><h1>{title}</h1><p data-testid="admin-page-subtitle">Every saved change updates MobileCart live data.</p></div><label className="admin-quick-find"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Find in ${title}`} data-testid="admin-section-search-input" /></label><div className="admin-actions"><span className="live-pill" data-testid="admin-live-status">LIVE DATA</span><Link to="/" data-testid="admin-store-link">View Store</Link></div></header>; }

function Dashboard() { const [data, setData] = useState(null); useEffect(() => { api.get("/api/admin/dashboard").then(({ data: response }) => setData(response)).catch((error) => toast.error(apiError(error))); }, []); if (!data) return <div className="empty-state" data-testid="admin-dashboard-loading"><Package size={30} /><h3>Loading live dashboard…</h3></div>; const { metrics, recent_orders: orders } = data; return <div data-testid="admin-dashboard"><div className="admin-stats">{[["Live revenue", money(metrics.total_revenue), WalletCards], ["Orders", metrics.total_orders, Package], ["Customers", metrics.total_users, Users], ["Published products", metrics.total_products, Tags], ["Auctions", metrics.total_auctions, Gavel]].map(([label, value, Icon]) => <section className="stat" key={label} data-testid={`metric-${label.toLowerCase().replaceAll(" ", "-")}`}><span className="stat-icon"><Icon /></span><small>{label}</small><strong>{value}</strong><em>Live sync</em></section>)}</div><section className="admin-panel table-panel admin-wide"><div className="panel-head"><div><h2>Recent orders</h2><span>Website orders update this panel automatically.</span></div><Link to="/admin/orders" data-testid="dashboard-orders-link">Manage orders</Link></div><table data-testid="dashboard-orders-table"><thead><tr><th>Order</th><th>Total</th><th>Status</th><th>Date</th></tr></thead><tbody>{orders.length ? orders.map((order) => <tr key={order.id}><td>{order.order_number}</td><td>{money(order.total)}</td><td>{order.status}</td><td>{new Date(order.created_at).toLocaleDateString("en-IN")}</td></tr>) : <tr><td colSpan="4">No live orders yet</td></tr>}</tbody></table></section></div>; }

function Content({ section, query }) { const item = sectionGroups.find(([id]) => id === section) || sectionGroups[0]; const [, label, type] = item; if (type === "dashboard" || type === "reports") return <Dashboard />; if (type === "products") return <AdminProductManager query={query} />; if (type === "wallet") return <AdminWalletManager query={query} />; if (type === "categories") return <CategoryManager query={query} />; if (type === "users") return <UserManager query={query} />; if (type === "admin-users") return <UserManager admins query={query} />; if (type === "resource") return <AdminResourceManager resource={section} label={label} query={query} />; return <WorkflowManager kind={type} query={query} />; }

export default function AdminWorkspace() { const location = useLocation(); const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const segment = location.pathname.split("/")[2] || "dashboard"; const active = sectionGroups.some(([id]) => id === segment) ? segment : "dashboard"; const title = sectionGroups.find(([id]) => id === active)?.[1] || "Dashboard"; useEffect(() => setQuery(""), [active]); return <div className="admin-shell"><Sidebar active={active} open={open} onClose={() => setOpen(false)} /><main className="admin-main"><Header title={active === "dashboard" ? "MobileCart Live Control" : title} onMenu={() => setOpen(true)} query={query} setQuery={setQuery} /><Content section={active} query={query} /></main></div>; }