import { useCallback, useEffect, useState } from "react";
import { Check, Eye, X } from "lucide-react";
import { api, apiError } from "@/api";
import { toast } from "sonner";

export default function AdminReturnManager({ query = "" }) {
  const [claims, setClaims] = useState([]); const [selected, setSelected] = useState(null); const [reason, setReason] = useState("");
  const load = useCallback(() => api.get("/api/admin/returns?page_size=100").then(({ data }) => setClaims(data.items || data)).catch((error) => toast.error(apiError(error))), []);
  useEffect(() => { load(); const timer = setInterval(load, 1000); return () => clearInterval(timer); }, [load]);
  const decide = async (decision) => { try { await api.post(`/api/admin/returns/${selected.id}/decision`, { decision, reason: reason || (decision === "approve" ? "Evidence verified" : "Evidence does not meet return requirements") }); toast.success(`Return ${decision}d`); setSelected(null); load(); } catch (error) { toast.error(apiError(error)); } };
  const visible = claims.filter((item) => `${item.title} ${item.data?.reason || ""}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="admin-returns" data-testid="admin-return-manager"><div className="admin-panel table-panel"><div className="panel-head"><div><h2>Warranty return review</h2><span>{visible.length} claims · evidence required</span></div></div><div className="return-review-grid">{visible.map((item) => <article key={item.id} data-testid={`admin-return-${item.id}`}><span className={`status-${item.status === "approved" ? "live" : item.status === "disapproved" ? "draft" : "pending"}`}>{item.status.replaceAll("_", " ")}</span><h3>{item.title}</h3><p>{item.data?.reason?.replaceAll("_", " ")}</p><button onClick={() => { setSelected(item); setReason(item.data?.admin_reason || ""); }} data-testid={`review-return-${item.id}`}><Eye size={14} /> Review evidence</button></article>)}</div></div>{selected && <aside className="admin-order-drawer return-review-drawer" data-testid="admin-return-review-drawer"><div className="drawer-head"><div><span className="eyebrow">RETURN CLAIM</span><h2>{selected.title}</h2></div><button onClick={() => setSelected(null)}><X size={18} /></button></div><p className="return-reason-copy">Customer reason: <b>{selected.description}</b></p><div className="return-evidence-admin">{selected.data?.photo_file_ids?.map((fileId) => <img key={fileId} src={`/api/admin/media/${fileId}`} alt="Return evidence" />)}{selected.data?.video_file_id && <a href={`/api/admin/media/${selected.data.video_file_id}`} target="_blank" rel="noreferrer">Open one-minute device video</a>}</div><label>Decision reason<input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Required for customer" data-testid="return-decision-reason" /></label>{selected.status === "pending_admin_review" && <div className="drawer-actions"><button className="primary-btn" onClick={() => decide("approve")} data-testid="approve-return-button"><Check size={15} /> Approve</button><button onClick={() => decide("disapprove")} data-testid="disapprove-return-button">Disapprove</button></div>}</aside>}</section>;
}